import {
  BackgroundViewport,
  NetworkLayerDefinition,
} from './viewport-background.models'

export function createPhaseTwoLayers(
  viewport: BackgroundViewport,
): NetworkLayerDefinition[] {
  const scale = viewport.minDimension

  return [
    {
      id: 'deep-structure',
      lineColor: '#6ca8cc',
      pointColor: '#7eaecb',
      lineOpacity: 0.04,
      pointOpacity: 0.06,
      pointSize: clamp(scale * 0.00255, 1.75, 2.95),
      edgeDistanceFactor: 1.12,
      maxNeighborsPerNode: 4,
      pulseNodeCount: 2,
      pulseOpacity: 0.14,
      pulseSizeScale: 1.82,
      pulseSpeed: 0.72,
      zOffset: -0.2,
      renderOrder: 0,
      motion: {
        clusterOffsetRange: 0.082,
        viewportDriftRange: 0.16,
        scaleRange: 0.02,
        rotationRange: 0.012,
        nodeOffsetRange: 0.14,
        driftSpeed: 0.06,
        morphSpeed: 0.11,
        sweepSpeed: 0.07,
        deformationSpeed: 0.34,
        detailMix: 0.1,
      },
      clusters: [
        {
          anchorX: -0.84,
          anchorY: 0.56,
          radius: scale * 0.26,
          aspect: 1.36,
          nodeCount: 17,
          seed: 101,
        },
        {
          anchorX: -0.24,
          anchorY: 0.68,
          radius: scale * 0.24,
          aspect: 1.24,
          nodeCount: 16,
          seed: 223,
        },
        {
          anchorX: 0.42,
          anchorY: 0.62,
          radius: scale * 0.25,
          aspect: 1.28,
          nodeCount: 17,
          seed: 811,
        },
        {
          anchorX: 0.86,
          anchorY: 0.18,
          radius: scale * 0.22,
          aspect: 1.18,
          nodeCount: 15,
          seed: 919,
        },
        {
          anchorX: 0.66,
          anchorY: -0.34,
          radius: scale * 0.25,
          aspect: 1.22,
          nodeCount: 17,
          seed: 1237,
        },
        {
          anchorX: 0.08,
          anchorY: -0.54,
          radius: scale * 0.28,
          aspect: 1.26,
          nodeCount: 18,
          seed: 1439,
        },
        {
          anchorX: -0.52,
          anchorY: -0.46,
          radius: scale * 0.26,
          aspect: 1.34,
          nodeCount: 17,
          seed: 1543,
        },
        {
          anchorX: -0.86,
          anchorY: -0.02,
          radius: scale * 0.22,
          aspect: 1.18,
          nodeCount: 15,
          seed: 1657,
        },
        {
          anchorX: 0.14,
          anchorY: 0.08,
          radius: scale * 0.3,
          aspect: 1.42,
          nodeCount: 19,
          seed: 1777,
        },
        {
          anchorX: -0.58,
          anchorY: 0.08,
          radius: scale * 0.23,
          aspect: 1.2,
          nodeCount: 16,
          seed: 1879,
        },
        {
          anchorX: 0.84,
          anchorY: -0.74,
          radius: scale * 0.2,
          aspect: 1.16,
          nodeCount: 14,
          seed: 1999,
        },
      ],
    },
    {
      id: 'active-structure',
      lineColor: '#82c1e6',
      pointColor: '#a6d6ee',
      lineOpacity: 0.09,
      pointOpacity: 0.13,
      pointSize: clamp(scale * 0.003, 2.15, 3.45),
      edgeDistanceFactor: 1.04,
      maxNeighborsPerNode: 5,
      pulseNodeCount: 3,
      pulseOpacity: 0.2,
      pulseSizeScale: 2.05,
      pulseSpeed: 1.12,
      zOffset: 0,
      renderOrder: 1,
      motion: {
        clusterOffsetRange: 0.088,
        viewportDriftRange: 0.14,
        scaleRange: 0.024,
        rotationRange: 0.016,
        nodeOffsetRange: 0.18,
        driftSpeed: 0.09,
        morphSpeed: 0.14,
        sweepSpeed: 0.09,
        deformationSpeed: 0.46,
        detailMix: 0.14,
      },
      clusters: [
        {
          anchorX: -0.68,
          anchorY: 0.76,
          radius: scale * 0.17,
          aspect: 1.22,
          nodeCount: 13,
          seed: 307,
        },
        {
          anchorX: -0.06,
          anchorY: 0.52,
          radius: scale * 0.19,
          aspect: 1.32,
          nodeCount: 15,
          seed: 509,
        },
        {
          anchorX: 0.58,
          anchorY: 0.7,
          radius: scale * 0.17,
          aspect: 1.18,
          nodeCount: 13,
          seed: 701,
        },
        {
          anchorX: 0.82,
          anchorY: 0.08,
          radius: scale * 0.16,
          aspect: 1.16,
          nodeCount: 12,
          seed: 1031,
        },
        {
          anchorX: 0.74,
          anchorY: -0.54,
          radius: scale * 0.18,
          aspect: 1.2,
          nodeCount: 13,
          seed: 1291,
        },
        {
          anchorX: 0.08,
          anchorY: -0.76,
          radius: scale * 0.18,
          aspect: 1.22,
          nodeCount: 14,
          seed: 1409,
        },
        {
          anchorX: -0.46,
          anchorY: -0.62,
          radius: scale * 0.19,
          aspect: 1.28,
          nodeCount: 15,
          seed: 1523,
        },
        {
          anchorX: -0.82,
          anchorY: -0.16,
          radius: scale * 0.16,
          aspect: 1.18,
          nodeCount: 12,
          seed: 1627,
        },
        {
          anchorX: -0.4,
          anchorY: 0.04,
          radius: scale * 0.2,
          aspect: 1.3,
          nodeCount: 15,
          seed: 1741,
        },
        {
          anchorX: -0.22,
          anchorY: -0.08,
          radius: scale * 0.16,
          aspect: 1.24,
          nodeCount: 13,
          seed: 1867,
        },
        {
          anchorX: 0.46,
          anchorY: 0.18,
          radius: scale * 0.17,
          aspect: 1.2,
          nodeCount: 13,
          seed: 2017,
        },
      ],
    },
  ]
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max)
}
